version: '3.2'

networks:
  kbtg-go-network:

services:
  dblocal:
    image: postgres:12.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: go-example-db
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - kbtg-go-network